version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    restart: always

  backend:
    image: <dockerhub-username>/mean-backend
    container_name: backend
    environment:
      MONGO_URL: mongodb://mongo:27017/dd_db
    depends_on:
      - mongo
    restart: always

  frontend:
    image: <dockerhub-username>/mean-frontend
    container_name: frontend
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  mongo-data:
